---
title: "Modelo Ansiedad"
author: "Alejandro Ramos Usaj"
date: "2023-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(marginaleffects_posterior_interval = "hdi")
options(marginaleffects_posterior_center = mean)
```


```{r}
library(brms)
library(tidybayes)
library(tidyverse)
library(bayesrules)
library(bayesplot)
library(marginaleffects)
```



```{r}
#Load data
load('../data/exp1_data.RData')

#Compute influence score based on Zanete and factor column for good/bad news 
dexp1 <- dexp1 %>%
  mutate(
    influencia = (p2-p1)/(pT-p1),
    news = factor(ifelse(I==0, "bad", "good")),
    subj = as.integer(subj)
  )
```



```{r}
ggplot(dexp1, aes(x = scoreAnsiedad, y = p1)) + 
  geom_jitter() +
  geom_smooth()
```

```{r}
ggplot(dexp1,
       aes(x = scoreAnsiedad, y = p1)) + 
  geom_boxplot(aes(group = cut_width(scoreOptimismo, 1)))
```

```{r}
ggplot(
  dexp1,
  aes(x = p1, group = subj, color = scoreAnsiedad)
) +
  geom_density()
```


```{r}
filtered_data <- dexp1 |> filter(p1 > 0 & p1 < 1)
```


```{r}
beta_model <- brm(
  bf(p1 ~ scoreAnsiedad + (1|subj),
     phi ~ (1|subj)),
  data = filtered_data,
  family = Beta(),
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234
)
```


```{r}
broom.mixed::tidy(beta_model)
```


```{r}
avg_slopes(beta_model)
```


```{r}
slopes(
  beta_model,
  newdata = datagrid(scoreAnsiedad = seq(17,37,1), subj = 1:33)
) |>
  ggplot(
    aes(x = scoreAnsiedad, y = estimate, ymin = conf.low, ymax = conf.high)
  ) +
  geom_line(aes(group = subj), color = 'grey') +
  geom_line(
    data = slopes(beta_model, newdata = data.frame(scoreAnsiedad = seq(17,37,1), subj = -1), re_formula = NA),
    linetype = 'dashed', size = 1
  ) +
  theme_tidybayes() + xlab("Anxiety") + ylab("Slope")
```



```{r}
avg_predictions(beta_model, variables = 'scoreAnsiedad') |> posterior_draws() |>
  ggplot(
    aes(x = scoreAnsiedad, y = draw)
  ) +
  stat_lineribbon(point_interval = 'mean_hdi') + scale_fill_brewer('Posterior credible interval') + 
  xlab("Anxiety") + ylab("Posterior Prediction") +
  theme_tidybayes() + theme(legend.position = 'bottom')
```

